routes/admin.php
<?php
/**
 * Admin Routes
 */

Route::group([
     'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.',
     'middleware' => ['role:admin'],
 ], function () {
    Route::resource('airlines', 'AirlinesController');

    Route::match(['get', 'put'], 'airports/fuel', 'AirportController@fuel');
    Route::resource('airports', 'AirportController');

    Route::resource('fares', 'FareController');

    # subfleet
    Route::resource('subfleets', 'SubfleetController');
    Route::match(['get', 'post', 'put', 'delete'], 'subfleets/{id}/fares', 'SubfleetController@fares');

    # aircraft and fare associations
    Route::resource('aircraft', 'AircraftController');

    # flights and aircraft associations
    Route::resource('flights', 'FlightController');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/fields', 'FlightController@fields');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/subfleets', 'FlightController@subfleets');

    # rankings
    Route::resource('ranks', 'RankController');
    Route::match(['get', 'post', 'put', 'delete'], 'ranks/{id}/subfleets', 'RankController@subfleets');

    # view/update settings
    Route::match(['get'], 'settings', 'SettingsController@index');
    Route::match(['post', 'put'], 'settings', 'SettingsController@update');

    # pirep related routes
    Route::resource('pireps', 'PirepController');
    Route::match(['get'], 'pireps/pending', 'PirepController@pending');
    Route::match(['post', 'put'], 'pireps/{id}/status', 'PirepController@status');

    Route::resource('pirepfields', 'PirepFieldController');

    Route::resource('users', 'UserController');

    # defaults
    Route::get('', ['uses' => 'DashboardController@index']);
    Route::get('/', ['uses' => 'DashboardController@index']);
    Route::get('/dashboard', ['uses' => 'DashboardController@index', 'name' => 'dashboard']);
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

/**
 * User doesn't need to be logged in for these
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.'
], function() {
    Route::get('/r/{id}', 'PirepController@show')->name('pirep.show.public');
    Route::get('/p/{id}', 'ProfileController@show')->name('profile.show.public');
});

/**
 * These are only visible to a logged in user
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.',
    'middleware' => ['role:admin|user'],
], function () {
    Route::resource('dashboard', 'DashboardController');

    Route::get('flights/search', 'FlightController@search')->name('flights.search');
    Route::match(['post'], '/flights/save', 'FlightController@save')->name('flights.save');
    Route::resource('flights', 'FlightController');

    Route::resource('profile', 'ProfileController');
    Route::resource('pireps', 'PirepController');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

require base_path('routes/admin.php');

app/Models/PirepField.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class PirepField
 *
 * @package App\Models
 */
class PirepField extends Model
{
    public $table = 'pirep_fields';

    public $fillable
        = [
            'name',
            'required',
        ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts
        = [
            'name'     => 'string',
            'required' => 'integer',
        ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules
        = [
            'name' => 'required',
        ];
}

app/Http/Controllers/Admin/PirepFieldController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreatePirepFieldRequest;
use App\Http\Requests\UpdatePirepFieldRequest;
use App\Repositories\PirepFieldRepository;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class PirepFieldController extends BaseController
{
    /** @var  PirepFieldRepository */
    private $pirepFieldRepo;

    public function __construct(PirepFieldRepository $pirepFieldRepo)
    {
        $this->pirepFieldRepo = $pirepFieldRepo;
    }

    /**
     * Display a listing of the PirepField.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->pirepFieldRepo->pushCriteria(new RequestCriteria($request));
        $fields = $this->pirepFieldRepo->all();

        return view('admin.pirepFields.index', [
            'fields' => $fields,
        ]);
    }

    /**
     * Show the form for creating a new PirepField.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.pirepFields.create');
    }

    /**
     * Store a newly created PirepField in storage.
     *
     * @param CreatePirepFieldRequest $request
     *
     * @return Response
     */
    public function store(CreatePirepFieldRequest $request)
    {
        $input = $request->all();

        $field = $this->pirepFieldRepo->create($input);

        Flash::success('PirepField saved successfully.');
        return redirect(route('admin.pirepFields.index'));
    }

    /**
     * Display the specified PirepField.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $field = $this->pirepFieldRepo->findWithoutFail($id);

        if (empty($field)) {
            Flash::error('PirepField not found');
            return redirect(route('admin.pirepFields.index'));
        }

        return view('admin.pirepFields.show', [
            'field' => $field,
        ]);
    }

    /**
     * Show the form for editing the specified PirepField.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $field = $this->pirepFieldRepo->findWithoutFail($id);

        if (empty($field)) {
            Flash::error('PirepField not found');
            return redirect(route('admin.pirepFields.index'));
        }

        return view('admin.pirepFields.edit', [
            'field' => $field,
        ]);
    }

    /**
     * Update the specified PirepField in storage.
     *
     * @param  int              $id
     * @param UpdatePirepFieldRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePirepFieldRequest $request)
    {
        $field = $this->pirepFieldRepo->findWithoutFail($id);

        if (empty($field)) {
            Flash::error('PirepField not found');
            return redirect(route('admin.pirepFields.index'));
        }

        $field = $this->pirepFieldRepo->update($request->all(), $id);

        Flash::success('PirepField updated successfully.');
        return redirect(route('admin.pirepFields.index'));
    }

    /**
     * Remove the specified PirepField from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $field = $this->pirepFieldRepo->findWithoutFail($id);

        if (empty($field)) {
            Flash::error('PirepField not found');
            return redirect(route('admin.pirepFields.index'));
        }

        $this->pirepFieldRepo->delete($id);

        Flash::success('PirepField deleted successfully.');
        return redirect(route('admin.pirepFields.index'));
    }
}

resources/views/admin/pirep_fields/create.blade.php
@extends('admin.app')

@section('content')
    <section class="content-header">
        <h1>Add PIREP Field</h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.pirepfields.store']) !!}
                        @include('admin.pirep_fields.fields')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pirep_fields/edit.blade.php
@extends('admin.app')

@section('content')
    <section class="content-header">
        <h1>Edit "{!! $field->name !!}"</h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($field, ['route' => ['admin.pirepfields.update', $field->id], 'method' => 'patch']) !!}
                        @include('admin.pirep_fields.fields')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/pirep_fields/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Required Field -->
<div class="form-group col-sm-6">
    {!! Form::label('required', 'Required:') !!}
    {!! Form::text('required', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.pirepfields.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/pirep_fields/index.blade.php
@extends('admin.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">PIREP Fields</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('admin.pirepfields.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.pirep_fields.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pirep_fields/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>{!! $pirepFields->name !!}</h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.pirep_fields.show_fields')
                    <a href="{!! route('admin.pirepfields.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pirep_fields/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $field->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $field->name !!}</p>
</div>

<!-- Required Field -->
<div class="form-group">
    {!! Form::label('required', 'Required:') !!}
    <p>{!! $field->required !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $field->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $field->updated_at !!}</p>
</div>

resources/views/admin/pirep_fields/table.blade.php
<table class="table table-hover table-responsive" id="pirepFields-table">
    <thead>
        <th>Name</th>
        <th>Required</th>
        <th></th>
    </thead>
    <tbody>
    @foreach($fields as $field)
        <tr>
            <td>{!! $field->name !!}</td>
            <td>{!! $field->required !!}</td>
            <td>
                {!! Form::open(['route' => ['admin.pirepfields.destroy', $field->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    {{--<a href="{!! route('admin.pirepfields.show', [$field->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('admin.pirepfields.edit', [$field->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>--}}
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>