routes/admin.php
<?php
/**
 * Admin Routes
 */

Route::group([
     'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.',
     'middleware' => ['role:admin'],
 ], function () {
    Route::resource('airlines', 'AirlinesController');

    Route::match(['get', 'put'], 'airports/fuel', 'AirportController@fuel');
    Route::resource('airports', 'AirportController');

    Route::resource('fares', 'FareController');

    # subfleet
    Route::resource('subfleets', 'SubfleetController');
    Route::match(['get', 'post', 'put', 'delete'], 'subfleets/{id}/fares', 'SubfleetController@fares');

    # aircraft and fare associations
    Route::resource('aircraft', 'AircraftController');

    # flights and aircraft associations
    Route::resource('flights', 'FlightController');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/fields', 'FlightController@fields');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/subfleets', 'FlightController@subfleets');

    # rankings
    Route::resource('ranks', 'RankController');
    Route::match(['get', 'post', 'put', 'delete'], 'ranks/{id}/subfleets', 'RankController@subfleets');

    # view/update settings
    Route::match(['get'], 'settings', 'SettingsController@index');
    Route::match(['post', 'put'], 'settings', 'SettingsController@update');

    # pirep related routes
    Route::resource('pireps', 'PirepController');
    Route::match(['get'], 'pireps/pending', 'PirepController@pending');
    Route::match(['post', 'put'], 'pireps/{id}/status', 'PirepController@status');

    Route::resource('pirepfields', 'PirepFieldController');

    Route::resource('users', 'UserController');

    # defaults
    Route::get('', ['uses' => 'DashboardController@index']);
    Route::get('/', ['uses' => 'DashboardController@index']);
    Route::get('/dashboard', ['uses' => 'DashboardController@index', 'name' => 'dashboard']);
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

/**
 * User doesn't need to be logged in for these
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.'
], function() {
    Route::get('/r/{id}', 'PirepController@show')->name('pirep.show.public');
    Route::get('/p/{id}', 'ProfileController@show')->name('profile.show.public');
});

/**
 * These are only visible to a logged in user
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.',
    'middleware' => ['role:admin|user'],
], function () {
    Route::resource('dashboard', 'DashboardController');

    Route::get('flights/search', 'FlightController@search')->name('flights.search');
    Route::match(['post'], '/flights/save', 'FlightController@save')->name('flights.save');
    Route::resource('flights', 'FlightController');

    Route::resource('profile', 'ProfileController');
    Route::resource('pireps', 'PirepController');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

require base_path('routes/admin.php');

app/Models/Aircraft.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Aircraft
 *
 * @package App\Models
 * @version June 9, 2017, 1:06 am UTC
 */
class Aircraft extends Model
{
    public $table = 'aircraft';

    protected $dates = ['deleted_at'];

    public $fillable
        = [
            'subfleet_id',
            'airport_id',
            'name',
            'registration',
            'tail_number',
            'active',
        ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts
        = [
            'subfleet_id'  => 'string',
            'name'         => 'string',
            'registration' => 'string',
            'active'       => 'boolean',
        ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules
        = [
            'name'         => 'required',
            'active'       => '',
        ];

    /**
     * foreign keys
     */

    public function airport()
    {
        return $this->belongsTo('App\Models\Airport', 'airport_id');
    }

    public function subfleet()
    {
        return $this->belongsTo('App\Models\Subfleet', 'subfleet_id');
    }
}

app/Http/Controllers/Admin/AircraftController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Subfleet;
use App\Http\Requests\CreateAircraftRequest;
use App\Http\Requests\UpdateAircraftRequest;
use App\Repositories\AircraftRepository;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;


class AircraftController extends BaseController
{
    private $aircraftRepository;

    public function __construct(
        AircraftRepository $aircraftRepo
    ) {
        $this->aircraftRepository = $aircraftRepo;
    }

    /**
     * Display a listing of the Aircraft.
     */
    public function index(Request $request)
    {
        $this->aircraftRepository->pushCriteria(new RequestCriteria($request));
        $aircraft = $this->aircraftRepository->all();

        return view('admin.aircraft.index', [
            'aircraft', $aircraft
        ]);
    }

    /**
     * Show the form for creating a new Aircraft.
     */
    public function create()
    {
        return view('admin.aircraft.create', [
            'subfleets' => Subfleet::all()->pluck('name', 'id'),
        ]);
    }

    /**
     * Store a newly created Aircraft in storage.
     */
    public function store(CreateAircraftRequest $request)
    {
        $input = $request->all();
        $aircraft = $this->aircraftRepository->create($input);

        Flash::success('Aircraft saved successfully.');
        return redirect(route('admin.aircraft.index'));
    }

    /**
     * Display the specified Aircraft.
     */
    public function show($id)
    {
        $aircraft = $this->aircraftRepository->findWithoutFail($id);

        if (empty($aircraft)) {
            Flash::error('Aircraft not found');
            return redirect(route('admin.aircraft.index'));
        }

        return view('admin.aircraft.show', [
            'aircraft'    => $aircraft,
        ]);
    }

    /**
     * Show the form for editing the specified Aircraft.
     */
    public function edit($id)
    {
        $aircraft = $this->aircraftRepository->findWithoutFail($id);

        if (empty($aircraft)) {
            Flash::error('Aircraft not found');
            return redirect(route('admin.aircraft.index'));
        }

        return view('admin.aircraft.edit', [
            'subfleets' => Subfleet::all()->pluck('name', 'id'),
            'aircraft'  => $aircraft,
        ]);
    }

    /**
     * Update the specified Aircraft in storage.
     */
    public function update($id, UpdateAircraftRequest $request)
    {
        $aircraft = $this->aircraftRepository->findWithoutFail($id);

        if (empty($aircraft)) {
            Flash::error('Aircraft not found');
            return redirect(route('admin.aircraft.index'));
        }

        $this->aircraftRepository->update($request->all(), $id);

        Flash::success('Aircraft updated successfully.');
        return redirect(route('admin.aircraft.index'));
    }

    /**
     * Remove the specified Aircraft from storage.
     */
    public function destroy($id)
    {
        $aircraft = $this->aircraftRepository->findWithoutFail($id);

        if (empty($aircraft)) {
            Flash::error('Aircraft not found');
            return redirect(route('admin.aircraft.index'));
        }

        $this->aircraftRepository->delete($id);

        Flash::success('Aircraft deleted successfully.');
        return redirect(route('admin.aircraft.index'));
    }

}

resources/views/admin/aircraft/create.blade.php
@extends('admin.app')

@section('content')
    <section class="content-header">
        <h1>
            Aircraft
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.aircraft.store']) !!}

                        @include('admin.aircraft.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/aircraft/edit.blade.php
@extends('admin.app')
@section('title', "Edit \"$aircraft->name\"")
@section('content')
<div class="card border-blue-bottom">
   <div class="content">
       @include('adminlte-templates::common.errors')
       {!! Form::model($aircraft, ['route' => ['admin.aircraft.update', $aircraft->id], 'method' => 'patch']) !!}

            @include('admin.aircraft.fields')

       {!! Form::close() !!}
   </div>
</div>
@endsection

resources/views/admin/aircraft/fields.blade.php
<div class="row">
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('subfleet_id', 'Subfleet:') !!}
    {!! Form::select('subfleet_id', $subfleets, null, ['class' => 'form-control select2', 'placeholder' => 'Select Subfleet']) !!}
</div>

<!-- Registration Field -->
<div class="form-group col-sm-6">
    {!! Form::label('registration', 'Registration:') !!}
    {!! Form::text('registration', null, ['class' => 'form-control']) !!}
</div>

<!-- Tail Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tail_number', 'Tail Number:') !!}
    {!! Form::text('tail_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Active Field -->
<div class="form-group col-12">
    {!! Form::label('active', 'Active:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('active', 0, false) !!}
        {!! Form::checkbox('active', 1, null) !!}
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    <div class="pull-right">
        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('admin.aircraft.index') !!}" class="btn btn-default">Cancel</a>
    </div>
</div>
</div>

resources/views/admin/aircraft/index.blade.php
@extends('admin.app')

@section('title', 'Aircraft')
@section('actions')
    <li>
        <a href="{!! url('/admin/subfleets') !!}">
            <i class="ti-files"></i>
            Subfleets</a>
    </li>
    <li>
        <a href="{!! route('admin.aircraft.create') !!}">
            <i class="ti-plus"></i>
            New Aircraft</a>
    </li>
@endsection

@section('content')
    <div class="card">
        @include('admin.aircraft.table')
    </div>
@endsection

resources/views/admin/aircraft/show.blade.php
@extends('admin.app')

@section('content')
<section class="content-header">
    <h1 class="pull-left">{!! $aircraft->name !!}</h1>
    <h1 class="pull-right">
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('admin.aircraft.edit', $aircraft->id) !!}">Edit</a>
    </h1>
</section>
<section class="content">
    <div class="clearfix"></div>
    <div class="row">
        @include('admin.aircraft.show_fields')
    </div>
</section>
@endsection
@section('scripts')
<script>
$(document).ready(function() {
    $(".ac-fare-dropdown").select2();
    $('#aircraft_fares a').editable({
        type: 'text',
        mode: 'inline',
        emptytext: 'default',
        url: '/admin/aircraft/{!! $aircraft->id !!}/fares',
        title: 'Enter override value',
        ajaxOptions: { 'type': 'put'},
        params: function(params) {
          return {
              fare_id: params.pk,
              name: params.name,
              value: params.value
          }
        }
    });

    $(document).on('submit', 'form.rm_fare', function(event) {
        event.preventDefault();
        $.pjax.submit(event, '#aircraft_fares_wrapper', {push: false});
    });
});
</script>
@endsection

resources/views/admin/aircraft/show_fields.blade.php
<!-- Icao Field -->
<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">{!! Form::label('airport_id', 'Location') !!}</h3>
        </div>
        <div class="box-body">
            <p class="lead">
            @if($aircraft->airport)
                {!! $aircraft->airport->icao !!}</p>
            @endif
        </div>
    </div>
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            {{--<i class="fa fa-text-width"></i>--}}
            <h3 class="box-title">{!! Form::label('name', 'Name') !!}</h3>
        </div>
        <div class="box-body"><p class="lead">{!! $aircraft->name !!}</p></div>
    </div>
</div>

<!-- Registration Field -->
<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            {{--<i class="fa fa-text-width"></i>--}}
            <h3 class="box-title">{!! Form::label('registration', 'Registration') !!}/
                {!! Form::label('tail_number', 'Tail Number') !!}</h3>
        </div>
        <div class="box-body"><p class="lead">{!! $aircraft->registration !!}/{!! $aircraft->tail_number !!}</p></div>
    </div>
</div>

<!-- Active Field -->
<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            {{--<i class="fa fa-text-width"></i>--}}
            <h3 class="box-title">{!! Form::label('active', 'Active:') !!}</h3>
        </div>
        <div class="box-body"><p class="lead">@if ($aircraft->active == '1') yes @else no @endif</p></div>
    </div>
</div>

resources/views/admin/aircraft/table.blade.php
<table class="table table-hover table-responsive" id="aircrafts-table">
    <thead>
        <th>Subfleet</th>
        <th>Name</th>
        <th>Registration</th>
        <th style="text-align: center;">Active</th>
        <th style="text-align: right;"></th>
    </thead>
    <tbody>
    @foreach($aircraft as $ac)
        <tr>
            <td>
                @if($ac->subfleet_id)
                    <a href="{!! route('admin.subfleets.edit', [$ac->subfleet_id]) !!}">
                    {!! $ac->subfleet->name !!}
                    </a>
                @else
                    -
                @endif
            </td>
            <td><a href="{!! route('admin.aircraft.edit', [$ac->id]) !!}">{!! $ac->name !!}</a></td>
            <td>{!! $ac->registration !!}</td>
            <td style="text-align: center;">
                @if($ac->active == 1)
                    <span class="label label-success">Active</span>
                @else
                    <span class="label label-default">Inactive</span>
                @endif
            </td>
            <td style="width: 10%; text-align: right;">
                {!! Form::open(['route' => ['admin.aircraft.destroy', $ac->id], 'method' => 'delete']) !!}
                <a href="{!! route('admin.aircraft.edit', [$ac->id]) !!}" class='btn btn-sm btn-success btn-icon'>
                    <i class="fa fa-pencil-square-o"></i>
                </a>
                {!! Form::button('<i class="fa fa-times"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger btn-icon', 'onclick' => "return confirm('Are you sure?')"]) !!}
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>