routes/admin.php
<?php
/**
 * Admin Routes
 */

Route::group([
     'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.',
     'middleware' => ['role:admin'],
 ], function () {
    Route::resource('airlines', 'AirlinesController');

    Route::match(['get', 'put'], 'airports/fuel', 'AirportController@fuel');
    Route::resource('airports', 'AirportController');

    Route::resource('fares', 'FareController');

    # subfleet
    Route::resource('subfleets', 'SubfleetController');
    Route::match(['get', 'post', 'put', 'delete'], 'subfleets/{id}/fares', 'SubfleetController@fares');

    # aircraft and fare associations
    Route::resource('aircraft', 'AircraftController');

    # flights and aircraft associations
    Route::resource('flights', 'FlightController');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/fields', 'FlightController@fields');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/subfleets', 'FlightController@subfleets');

    # rankings
    Route::resource('ranks', 'RankController');
    Route::match(['get', 'post', 'put', 'delete'], 'ranks/{id}/subfleets', 'RankController@subfleets');

    # view/update settings
    Route::match(['get'], 'settings', 'SettingsController@index');
    Route::match(['post', 'put'], 'settings', 'SettingsController@update');

    # pirep related routes
    Route::resource('pireps', 'PirepController');
    Route::match(['get'], 'pireps/pending', 'PirepController@pending');
    Route::match(['post', 'put'], 'pireps/{id}/status', 'PirepController@status');

    Route::resource('pirepfields', 'PirepFieldController');

    Route::resource('users', 'UserController');

    # defaults
    Route::get('', ['uses' => 'DashboardController@index']);
    Route::get('/', ['uses' => 'DashboardController@index']);
    Route::get('/dashboard', ['uses' => 'DashboardController@index', 'name' => 'dashboard']);
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

/**
 * User doesn't need to be logged in for these
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.'
], function() {
    Route::get('/r/{id}', 'PirepController@show')->name('pirep.show.public');
    Route::get('/p/{id}', 'ProfileController@show')->name('profile.show.public');
});

/**
 * These are only visible to a logged in user
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.',
    'middleware' => ['role:admin|user'],
], function () {
    Route::resource('dashboard', 'DashboardController');

    Route::get('flights/search', 'FlightController@search')->name('flights.search');
    Route::match(['post'], '/flights/save', 'FlightController@save')->name('flights.save');
    Route::resource('flights', 'FlightController');

    Route::resource('profile', 'ProfileController');
    Route::resource('pireps', 'PirepController');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

require base_path('routes/admin.php');

app/Models/Pirep.php
<?php

namespace App\Models;

use Eloquent as Model;
use App\Models\Traits\Uuids;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Pirep
 *
 * @package App\Models
 */
class Pirep extends Model
{
    use Uuids;
    use SoftDeletes;

    public $table = 'pireps';
    public $incrementing = false;

    protected $dates = ['deleted_at'];

    public $fillable = [
        'user_id',
        'flight_id',
        'flight_number',
        'route_code',
        'route_leg',
        'airline_id',
        'aircraft_id',
        'flight_time',
        'dpt_airport_id',
        'arr_airport_id',
        'fuel_used',
        'source',
        'level',
        'route',
        'notes',
        'status',
        'raw_data',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'flight_time' => 'integer',
        'level'       => 'integer',
        'fuel_used'   => 'integer',
        'source'      => 'integer',
        'status'      => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules
        = [
            'dpt_airport_id' => 'required',
            'arr_airport_id' => 'required',
        ];

    /**
     * @return string
     */
    public function getFlightId()
    {
        $flight_id = $this->airline->code;
        if($this->flight_id) {
            $flight_id .= $this->flight->flight_number;
        } else {
            $flight_id .= $this->flight_number;
        }

        return $flight_id;
    }

    /**
     * Foreign Keys
     */
    public function aircraft()
    {
        return $this->belongsTo('App\Models\Aircraft', 'aircraft_id');
    }

    public function airline()
    {
        return $this->belongsTo('App\Models\Airline', 'airline_id');
    }

    public function arr_airport()
    {
        return $this->belongsTo('App\Models\Airport', 'arr_airport_id');
    }

    public function dpt_airport()
    {
        return $this->belongsTo('App\Models\Airport', 'dpt_airport_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\PirepComment', 'pirep_id');
    }

    public function events()
    {
        return $this->hasMany('App\Models\PirepEvent', 'pirep_id');
    }

    public function fields()
    {
        return $this->hasMany('App\Models\PirepFieldValues', 'pirep_id');
    }

    public function flight()
    {
        return $this->belongsTo('App\Models\Flight', 'flight_id');
    }

    public function pilot()
    {
        return $this->user();
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

}

app/Http/Controllers/Admin/PirepController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreatePirepRequest;
use App\Http\Requests\UpdatePirepRequest;
use App\Repositories\AircraftRepository;
use App\Repositories\AirlineRepository;
use App\Repositories\AirportRepository;
use App\Repositories\PirepRepository;
use App\Services\PIREPService;
use Illuminate\Http\Request;
use Flash;
use Log;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Facades\Utils;


class PirepController extends BaseController
{
    private $airportRepo,
            $airlineRepo,
            $pirepRepo,
            $aircraftRepo,
        $pirepSvc;

    public function __construct(
        AirportRepository $airportRepo,
        AirlineRepository $airlineRepo,
        AircraftRepository $aircraftRepo,
        PirepRepository $pirepRepo,
        PIREPService $pirepSvc
    ) {
        $this->airportRepo = $airportRepo;
        $this->airlineRepo = $airlineRepo;
        $this->aircraftRepo = $aircraftRepo;
        $this->pirepRepo = $pirepRepo;
        $this->pirepSvc = $pirepSvc;
    }

    public function aircraftList()
    {
        $retval = [];
        $all_aircraft = $this->aircraftRepo->all();

        foreach ($all_aircraft as $ac) {
            $retval[$ac->id] = $ac->subfleet->name.' - '.$ac->name.' ('.$ac->registration.')';
        }

        return $retval;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function index(Request $request)
    {
        $criterea = new RequestCriteria($request);
        $this->pirepRepo->pushCriteria($criterea);

        $pireps = $this->pirepRepo
                       ->orderBy('created_at', 'desc')
                       ->paginate();

        return view('admin.pireps.index', [
            'pireps' => $pireps
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function pending(Request $request)
    {
        $criterea = new RequestCriteria($request);
        $this->pirepRepo->pushCriteria($criterea);

        $pireps = $this->pirepRepo
            ->findWhere(['status' => config('enums.pirep_status.PENDING')])
            ->orderBy('created_at', 'desc')
            ->paginate();

        return view('admin.pireps.index', [
            'pireps' => $pireps
        ]);
    }

    /**
     * Show the form for creating a new Pirep.
     * @return Response
     */
    public function create()
    {
        return view('admin.pireps.create');
    }

    /**
     * @param CreatePirepRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(CreatePirepRequest $request)
    {
        $input = $request->all();
        $pirep = $this->pirepRepo->create($input);

        Flash::success('Pirep saved successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Display the specified Pirep.
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $pirep = $this->pirepRepo->find($id);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        return view('admin.pireps.show', [
            'pirep' => $pirep,
        ]);
    }

    /**
     * Show the form for editing the specified Pirep.
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);
        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $hms = Utils::secondsToTimeParts($pirep->flight_time);
        $pirep->hours = $hms['h'];
        $pirep->minutes = $hms['m'];

        return view('admin.pireps.edit', [
            'pirep' => $pirep,
            'airports' => $this->airportRepo->selectBoxList(),
            'airlines' => $this->airlineRepo->selectBoxList(),
            'aircraft' => $this->aircraftRepo->selectBoxList(),
        ]);
    }

    /**
     * @param $id
     * @param UpdatePirepRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update($id, UpdatePirepRequest $request)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);

        $pirep->flight_time = ((int)$request['hours'] * 60 * 60)
                            + ((int)$request['minutes'] * 60);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $pirep = $this->pirepRepo->update($request->all(), $id);

        Flash::success('Pirep updated successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Remove the specified Pirep from storage.
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $this->pirepRepo->delete($id);

        Flash::success('Pirep deleted successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Change or update the PIREP status
     * @param Request $request
     * @return \Illuminate\View\View
     */
    public function status(Request $request)
    {
        Log::info('PIREP status update call', [$request->toArray()]);

        $pirep = $this->pirepRepo->findWithoutFail($request->id);
        if($request->isMethod('post')) {
            $new_status = (int) $request->new_status;
            $pirep = $this->pirepSvc->changeStatus($pirep, $new_status);
        }

        $pirep->refresh();
        return view('admin.pireps.pirep_card', ['pirep' => $pirep]);
    }
}

app/Http/Controllers/Api/PirepController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Pirep;
use App\Models\Transformers\PirepTransformer;
use App\Http\Controllers\AppBaseController;


class PirepController extends AppBaseController
{
    public function get($id)
    {
        $pirep = Pirep::find($id);
        return fractal($pirep, new PirepTransformer())->respond();
    }
}

app/Http/Controllers/Frontend/PirepController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Repositories\Criteria\WhereCriteria;
use App\Services\PIREPService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

use App\Models\Pirep;
use App\Models\PirepField;

use App\Http\Controllers\Controller;
use App\Repositories\AirlineRepository;
use App\Repositories\AircraftRepository;
use App\Repositories\AirportRepository;
use App\Repositories\PirepRepository;
use App\Repositories\PirepFieldRepository;


class PirepController extends Controller
{
    private $airlineRepo,
            $aircraftRepo,
            $pirepRepo,
            $airportRepo,
            $pirepFieldRepo,
            $pirepSvc;

    public function __construct(
        AirlineRepository $airlineRepo,
        PirepRepository $pirepRepo,
        AircraftRepository $aircraftRepo,
        AirportRepository $airportRepo,
        PirepFieldRepository $pirepFieldRepo,
        PIREPService $pirepSvc
    ) {
        $this->airlineRepo = $airlineRepo;
        $this->aircraftRepo = $aircraftRepo;
        $this->pirepRepo = $pirepRepo;
        $this->airportRepo = $airportRepo;
        $this->pirepFieldRepo = $pirepFieldRepo;
        $this->pirepSvc = $pirepSvc;
    }

    public function index(Request $request)
    {
        $user = Auth::user();

        $where = ['user_id' => $user->id];
        $this->pirepRepo->pushCriteria(new WhereCriteria($request, $where));
        $pireps = $this->pirepRepo->orderBy('created_at', 'desc')->paginate();

        return $this->view('pireps.index', [
            'user' => $user,
            'pireps' => $pireps,
        ]);
    }

    public function create()
    {
        return $this->view('pireps.create', [
            'airports' => $this->airportRepo->selectBoxList(),
            'airlines' => $this->airlineRepo->selectBoxList(),
            'aircraft' => $this->aircraftRepo->selectBoxList(),
            'pirepfields' => $this->pirepFieldRepo->all(),
            'fieldvalues' => [],
        ]);
    }

    public function store(Request $request)
    {
        $pirep_fields = $request->all();

        // Create the main PIREP
        $pirep = new Pirep($pirep_fields);

        // Any special fields
        $pirep->pilot()->associate(Auth::user());
        $pirep->flight_time = ((int)$pirep_fields['hours'] * 60 * 60)
                            + ((int)$pirep_fields['minutes'] * 60);

        // The custom fields from the form
        $custom_fields = [];
        foreach($pirep_fields as $field_name => $field_val)
        {
            if (strpos($field_name, 'field_') === false) {
                continue;
            }

            $field_id = explode('field_', $field_name)[1];
            $cfield = PirepField::find($field_id);

            $custom_fields[] = [
                'name' => $cfield->name,
                'value' => $field_val,
                'source' => config('enums.sources.MANUAL')
            ];
        }

        $pirep = $this->pirepSvc->create($pirep, $custom_fields);

        //Flash::success('PIREP submitted successfully!');
        return redirect(route('frontend.pireps.index'));
    }

    public function show($id)
    {
        $pirep = Pirep::where('id', $id);
        return $this->view('pireps.show', [
            'pirep' => $pirep,
        ]);
    }
}

resources/views/layouts/default/pireps/create.blade.php
@extends('layouts.default.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h2 class="description">new pilot report</h2>
            @include('flash::message')
            {!! Form::open(['route' => 'frontend.pireps.store']) !!}

            @include('layouts.default.pireps.fields')

            {!! Form::close() !!}
        </div>
    </div>
@endsection
@section('scripts')
<script>
$(document).ready(function() {

});
</script>
@endsection

resources/views/layouts/default/pireps/fields.blade.php
<div class="row">
    <div class="col-12">
        <table class="table table-full-width">
            <thead>

            </thead>
            <tbody>
                <tr>
                    <td>Airline</td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::select('airline_id', $airlines, null, ['class' => 'custom-select select2']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>Flight Number/Code/Leg</td>
                    <td>
                        <div class="input-group form-group" style="max-width: 400px;">
                            {!! Form::text('flight_number', null, ['placeholder' => 'Flight Number', 'class' => 'form-control']) !!}
                            {!! Form::text('route_code', null, ['placeholder' => 'Code (optional)', 'class' => 'form-control']) !!}
                            {!! Form::text('route_leg', null, ['placeholder' => 'Leg (optional)', 'class' => 'form-control']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>Aircraft</td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::select('aircraft_id', $aircraft, null, ['class' => 'custom-select select2']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>Origin Airport</td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::select('dpt_airport_id', $airports, null, ['class' => 'custom-select select2']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>Arrival Airport</td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::select('arr_airport_id', $airports, null, ['class' => 'custom-select select2']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td class="align-text-top">Flight Time</td>
                    <td>
                        <div class="input-group" style="max-width: 200px;">
                            {!! Form::number('hours', null, ['class' => 'form-control', 'placeholder' => 'hours']) !!}
                            {!! Form::number('minutes', null, ['class' => 'form-control', 'placeholder' => 'minutes']) !!}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td class="align-text-top">Route</td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::textarea('route', null, ['class' => 'form-control', 'placeholder' => 'Route']) !!}
                        </div>
                    </td>
                </tr>

                {{--
                Write out the custom fields, and label if they're required
                --}}
                @foreach($pirepfields as $field)
                <tr>
                    <td>
                        {!! $field->name !!}
                        <span class="label label-danger">required</span>
                    </td>
                    <td>
                        <div class="input-group form-group">
                            <!--<span class="input-group-addon">
                                <i class="now-ui-icons users_single-02"></i>
                            </span>-->
                            {!! Form::text('field_'.$field->id, null, [
                                    'class' => 'form-control',
                                    'required' => $field->required,
                                ]) !!}
                        </div>
                    </td>
                </tr>
                @endforeach

                <tr>
                    <td class="align-text-top"><p class="">Notes</p></td>
                    <td>
                        <div class="input-group form-group">
                            {!! Form::textarea('notes', null, ['class' => 'form-control', 'placeholder' => 'Notes']) !!}
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12">
        <div class="float-right">
        <div class="form-group">
            {!! Form::submit('Submit PIREP', ['class' => 'btn btn-primary']) !!}
        </div>
        </div>
    </div>

</div>

resources/views/layouts/default/pireps/index.blade.php
@extends('layouts.default.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div style="float:right;">
            <a class="btn btn-primary pull-right btn-lg"
               style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('frontend.pireps.create') !!}">File New PIREP</a>
        </div>
        <h2 class="description">pilot reports</h2>
        @include('flash::message')
        @include('layouts.default.pireps.table')
    </div>
</div>
<div class="row">
    <div class="col-12 text-center">
        {{ $pireps->links('layouts.default.pagination.default') }}
    </div>
</div>
@endsection

resources/views/layouts/default/pireps/table.blade.php
@foreach($pireps as $pirep)
<div class="card border-blue-bottom">
    <div class="card-block" style="min-height: 0px">
        <div class="row">
            <div class="col-sm-2 text-center">
                <h5>
                    <a class="text-c" href="{!! route('frontend.pireps.show', [$pirep->id]) !!}">
                        {!! $pirep->airline->code !!}
                        @if($pirep->flight_id)
                            {!! $pirep->flight->flight_number !!}
                        @else
                            {!! $pirep->flight_number !!}
                        @endif
                    </a>
                </h5>
                <div>
                    @if($pirep->status == config('enums.pirep_status.PENDING'))
                        <div class="badge badge-warning">Pending</div>
                    @elseif($pirep->status == config('enums.pirep_status.ACCEPTED'))
                        <div class="badge badge-success">Accepted</div>
                    @else
                        <div class="badge badge-danger">Rejected</div>
                    @endif
                </div>
            </div>
            <div class="col-sm-10">
                <div class="row">
                    <div class="col-sm-4">
                        <div>
                            <span class="description">DEP&nbsp;</span>
                            {!! $pirep->dpt_airport->icao !!}&nbsp;
                            <span class="description">ARR&nbsp;</span>
                            {!! $pirep->arr_airport->icao !!}&nbsp;
                        </div>
                        <div><span class="description">Flight Time&nbsp;</span>
                            {!! Utils::secondsToTime($pirep->flight_time) !!}
                        </div>
                        <div><span class="description">Aircraft&nbsp;</span>
                            {!! $pirep->aircraft->registration !!} ({!! $pirep->aircraft->name !!})
                        </div>
                        <div>
                            <span class="description">Flight Level&nbsp;</span>
                            {!! $pirep->level !!}
                        </div>
                        <div>
                            <span class="description">File Date&nbsp;</span>
                            {!! $pirep->created_at !!}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <span class="description">more data&nbsp;</span>
                    </div>
                    <div class="col-sm-4">
                        <span class="description">more data&nbsp;</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endforeach