routes/admin.php
<?php
/**
 * Admin Routes
 */

Route::group([
     'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.',
     'middleware' => ['role:admin'],
 ], function () {
    Route::resource('airlines', 'AirlinesController');

    Route::match(['get', 'put'], 'airports/fuel', 'AirportController@fuel');
    Route::resource('airports', 'AirportController');

    Route::resource('fares', 'FareController');

    # subfleet
    Route::resource('subfleets', 'SubfleetController');
    Route::match(['get', 'post', 'put', 'delete'], 'subfleets/{id}/fares', 'SubfleetController@fares');

    # aircraft and fare associations
    Route::resource('aircraft', 'AircraftController');

    # flights and aircraft associations
    Route::resource('flights', 'FlightController');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/fields', 'FlightController@fields');
    Route::match(['get', 'post', 'put', 'delete'], 'flights/{id}/subfleets', 'FlightController@subfleets');

    # rankings
    Route::resource('ranks', 'RankController');
    Route::match(['get', 'post', 'put', 'delete'], 'ranks/{id}/subfleets', 'RankController@subfleets');

    # view/update settings
    Route::match(['get'], 'settings', 'SettingsController@index');
    Route::match(['post', 'put'], 'settings', 'SettingsController@update');

    # pirep related routes
    Route::resource('pireps', 'PirepController');
    Route::match(['get'], 'pireps/pending', 'PirepController@pending');
    Route::match(['post', 'put'], 'pireps/{id}/status', 'PirepController@status');

    Route::resource('pirepfields', 'PirepFieldController');

    Route::resource('users', 'UserController');

    # defaults
    Route::get('', ['uses' => 'DashboardController@index']);
    Route::get('/', ['uses' => 'DashboardController@index']);
    Route::get('/dashboard', ['uses' => 'DashboardController@index', 'name' => 'dashboard']);
});

routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

/**
 * User doesn't need to be logged in for these
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.'
], function() {
    Route::get('/r/{id}', 'PirepController@show')->name('pirep.show.public');
    Route::get('/p/{id}', 'ProfileController@show')->name('profile.show.public');
});

/**
 * These are only visible to a logged in user
 */
Route::group([
    'namespace' => 'Frontend', 'prefix' => '', 'as' => 'frontend.',
    'middleware' => ['role:admin|user'],
], function () {
    Route::resource('dashboard', 'DashboardController');

    Route::get('flights/search', 'FlightController@search')->name('flights.search');
    Route::match(['post'], '/flights/save', 'FlightController@save')->name('flights.save');
    Route::resource('flights', 'FlightController');

    Route::resource('profile', 'ProfileController');
    Route::resource('pireps', 'PirepController');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

require base_path('routes/admin.php');

app/Models/Pirep.php
<?php

namespace App\Models;

use Eloquent as Model;
use App\Models\Traits\Uuids;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Pirep
 *
 * @package App\Models
 */
class Pirep extends Model
{
    use Uuids;
    use SoftDeletes;

    public $table = 'pireps';
    public $incrementing = false;

    protected $dates = ['deleted_at'];

    public $fillable = [
        'user_id',
        'flight_id',
        'flight_number',
        'route_code',
        'route_leg',
        'airline_id',
        'aircraft_id',
        'flight_time',
        'dpt_airport_id',
        'arr_airport_id',
        'fuel_used',
        'source',
        'level',
        'route',
        'notes',
        'status',
        'raw_data',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'flight_time' => 'integer',
        'level'       => 'integer',
        'fuel_used'   => 'integer',
        'source'      => 'integer',
        'status'      => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules
        = [
            'dpt_airport_id' => 'required',
            'arr_airport_id' => 'required',
        ];

    /**
     * @return string
     */
    public function getFlightId()
    {
        $flight_id = $this->airline->code;
        if($this->flight_id) {
            $flight_id .= $this->flight->flight_number;
        } else {
            $flight_id .= $this->flight_number;
        }

        return $flight_id;
    }

    /**
     * Foreign Keys
     */
    public function aircraft()
    {
        return $this->belongsTo('App\Models\Aircraft', 'aircraft_id');
    }

    public function airline()
    {
        return $this->belongsTo('App\Models\Airline', 'airline_id');
    }

    public function arr_airport()
    {
        return $this->belongsTo('App\Models\Airport', 'arr_airport_id');
    }

    public function dpt_airport()
    {
        return $this->belongsTo('App\Models\Airport', 'dpt_airport_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\PirepComment', 'pirep_id');
    }

    public function events()
    {
        return $this->hasMany('App\Models\PirepEvent', 'pirep_id');
    }

    public function fields()
    {
        return $this->hasMany('App\Models\PirepFieldValues', 'pirep_id');
    }

    public function flight()
    {
        return $this->belongsTo('App\Models\Flight', 'flight_id');
    }

    public function pilot()
    {
        return $this->user();
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

}

app/Http/Controllers/Admin/PirepController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreatePirepRequest;
use App\Http\Requests\UpdatePirepRequest;
use App\Repositories\AircraftRepository;
use App\Repositories\AirlineRepository;
use App\Repositories\AirportRepository;
use App\Repositories\PirepRepository;
use App\Services\PIREPService;
use Illuminate\Http\Request;
use Flash;
use Log;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use App\Facades\Utils;


class PirepController extends BaseController
{
    private $airportRepo,
            $airlineRepo,
            $pirepRepo,
            $aircraftRepo,
        $pirepSvc;

    public function __construct(
        AirportRepository $airportRepo,
        AirlineRepository $airlineRepo,
        AircraftRepository $aircraftRepo,
        PirepRepository $pirepRepo,
        PIREPService $pirepSvc
    ) {
        $this->airportRepo = $airportRepo;
        $this->airlineRepo = $airlineRepo;
        $this->aircraftRepo = $aircraftRepo;
        $this->pirepRepo = $pirepRepo;
        $this->pirepSvc = $pirepSvc;
    }

    public function aircraftList()
    {
        $retval = [];
        $all_aircraft = $this->aircraftRepo->all();

        foreach ($all_aircraft as $ac) {
            $retval[$ac->id] = $ac->subfleet->name.' - '.$ac->name.' ('.$ac->registration.')';
        }

        return $retval;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function index(Request $request)
    {
        $criterea = new RequestCriteria($request);
        $this->pirepRepo->pushCriteria($criterea);

        $pireps = $this->pirepRepo
                       ->orderBy('created_at', 'desc')
                       ->paginate();

        return view('admin.pireps.index', [
            'pireps' => $pireps
        ]);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     */
    public function pending(Request $request)
    {
        $criterea = new RequestCriteria($request);
        $this->pirepRepo->pushCriteria($criterea);

        $pireps = $this->pirepRepo
            ->findWhere(['status' => config('enums.pirep_status.PENDING')])
            ->orderBy('created_at', 'desc')
            ->paginate();

        return view('admin.pireps.index', [
            'pireps' => $pireps
        ]);
    }

    /**
     * Show the form for creating a new Pirep.
     * @return Response
     */
    public function create()
    {
        return view('admin.pireps.create');
    }

    /**
     * @param CreatePirepRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(CreatePirepRequest $request)
    {
        $input = $request->all();
        $pirep = $this->pirepRepo->create($input);

        Flash::success('Pirep saved successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Display the specified Pirep.
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $pirep = $this->pirepRepo->find($id);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        return view('admin.pireps.show', [
            'pirep' => $pirep,
        ]);
    }

    /**
     * Show the form for editing the specified Pirep.
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);
        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $hms = Utils::secondsToTimeParts($pirep->flight_time);
        $pirep->hours = $hms['h'];
        $pirep->minutes = $hms['m'];

        return view('admin.pireps.edit', [
            'pirep' => $pirep,
            'airports' => $this->airportRepo->selectBoxList(),
            'airlines' => $this->airlineRepo->selectBoxList(),
            'aircraft' => $this->aircraftRepo->selectBoxList(),
        ]);
    }

    /**
     * @param $id
     * @param UpdatePirepRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update($id, UpdatePirepRequest $request)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);

        $pirep->flight_time = ((int)$request['hours'] * 60 * 60)
                            + ((int)$request['minutes'] * 60);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $pirep = $this->pirepRepo->update($request->all(), $id);

        Flash::success('Pirep updated successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Remove the specified Pirep from storage.
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $pirep = $this->pirepRepo->findWithoutFail($id);

        if (empty($pirep)) {
            Flash::error('Pirep not found');
            return redirect(route('admin.pireps.index'));
        }

        $this->pirepRepo->delete($id);

        Flash::success('Pirep deleted successfully.');
        return redirect(route('admin.pireps.index'));
    }

    /**
     * Change or update the PIREP status
     * @param Request $request
     * @return \Illuminate\View\View
     */
    public function status(Request $request)
    {
        Log::info('PIREP status update call', [$request->toArray()]);

        $pirep = $this->pirepRepo->findWithoutFail($request->id);
        if($request->isMethod('post')) {
            $new_status = (int) $request->new_status;
            $pirep = $this->pirepSvc->changeStatus($pirep, $new_status);
        }

        $pirep->refresh();
        return view('admin.pireps.pirep_card', ['pirep' => $pirep]);
    }
}

app/Http/Controllers/Api/PirepController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Pirep;
use App\Models\Transformers\PirepTransformer;
use App\Http\Controllers\AppBaseController;


class PirepController extends AppBaseController
{
    public function get($id)
    {
        $pirep = Pirep::find($id);
        return fractal($pirep, new PirepTransformer())->respond();
    }
}

app/Http/Controllers/Frontend/PirepController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Repositories\Criteria\WhereCriteria;
use App\Services\PIREPService;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

use App\Models\Pirep;
use App\Models\PirepField;

use App\Http\Controllers\Controller;
use App\Repositories\AirlineRepository;
use App\Repositories\AircraftRepository;
use App\Repositories\AirportRepository;
use App\Repositories\PirepRepository;
use App\Repositories\PirepFieldRepository;


class PirepController extends Controller
{
    private $airlineRepo,
            $aircraftRepo,
            $pirepRepo,
            $airportRepo,
            $pirepFieldRepo,
            $pirepSvc;

    public function __construct(
        AirlineRepository $airlineRepo,
        PirepRepository $pirepRepo,
        AircraftRepository $aircraftRepo,
        AirportRepository $airportRepo,
        PirepFieldRepository $pirepFieldRepo,
        PIREPService $pirepSvc
    ) {
        $this->airlineRepo = $airlineRepo;
        $this->aircraftRepo = $aircraftRepo;
        $this->pirepRepo = $pirepRepo;
        $this->airportRepo = $airportRepo;
        $this->pirepFieldRepo = $pirepFieldRepo;
        $this->pirepSvc = $pirepSvc;
    }

    public function index(Request $request)
    {
        $user = Auth::user();

        $where = ['user_id' => $user->id];
        $this->pirepRepo->pushCriteria(new WhereCriteria($request, $where));
        $pireps = $this->pirepRepo->orderBy('created_at', 'desc')->paginate();

        return $this->view('pireps.index', [
            'user' => $user,
            'pireps' => $pireps,
        ]);
    }

    public function create()
    {
        return $this->view('pireps.create', [
            'airports' => $this->airportRepo->selectBoxList(),
            'airlines' => $this->airlineRepo->selectBoxList(),
            'aircraft' => $this->aircraftRepo->selectBoxList(),
            'pirepfields' => $this->pirepFieldRepo->all(),
            'fieldvalues' => [],
        ]);
    }

    public function store(Request $request)
    {
        $pirep_fields = $request->all();

        // Create the main PIREP
        $pirep = new Pirep($pirep_fields);

        // Any special fields
        $pirep->pilot()->associate(Auth::user());
        $pirep->flight_time = ((int)$pirep_fields['hours'] * 60 * 60)
                            + ((int)$pirep_fields['minutes'] * 60);

        // The custom fields from the form
        $custom_fields = [];
        foreach($pirep_fields as $field_name => $field_val)
        {
            if (strpos($field_name, 'field_') === false) {
                continue;
            }

            $field_id = explode('field_', $field_name)[1];
            $cfield = PirepField::find($field_id);

            $custom_fields[] = [
                'name' => $cfield->name,
                'value' => $field_val,
                'source' => config('enums.sources.MANUAL')
            ];
        }

        $pirep = $this->pirepSvc->create($pirep, $custom_fields);

        //Flash::success('PIREP submitted successfully!');
        return redirect(route('frontend.pireps.index'));
    }

    public function show($id)
    {
        $pirep = Pirep::where('id', $id);
        return $this->view('pireps.show', [
            'pirep' => $pirep,
        ]);
    }
}

resources/views/admin/pireps/create.blade.php
@extends('admin.app')

@section('content')
    <section class="content-header">
        <h1>
            $MODEL_NAME_HUMAN$
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.pireps.store']) !!}

                        @include('admin.pireps.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pireps/edit.blade.php
@extends('admin.app')

@section('title', 'Edit ' . $pirep->getFlightId() )
@section('content')
<div class="content">
   @include('adminlte-templates::common.errors')
   <div class="card border-blue-bottom">
       <div class="content">
           {!! Form::model($pirep, ['route' => ['admin.pireps.update', $pirep->id], 'method' => 'patch']) !!}
                @include('admin.pireps.fields')
           {!! Form::close() !!}
       </div>
   </div>

    <div class="card border-blue-bottom">
        <div class="content">
            @include('admin.pireps.field_values')
        </div>
    </div>
</div>
@endsection
@include('admin.pireps.script')

resources/views/admin/pireps/field_values.blade.php
<div id="pirep_field_values_wrapper">
<table class="table table-responsive" id="flight-fields-table">
    <thead>
    <th>Name</th>
    <th>Value</th>
    <th>Source</th>
    <th style="text-align: right;">Actions</th>
    </thead>
    <tbody>
    @foreach($pirep->fields as $field)
        <tr>
            <td>{!! $field->name !!}</td>
            <td>
                <a class="inline" href="#" data-pk="{!! $field->id !!}" data-name="{!! $field->name !!}">{!! $field->value !!}</a>
            </td>
            <td>{!! $field->source !!}</td>
            <td style="width: 10%; text-align: right;" class="form-inline">
                {!! Form::open(['url' => '/admin/pireps/'.$pirep->id.'/fields',
                                'method' => 'delete',
                                'class' => 'pjax_form pirep_fields'
                                ]) !!}
                {!! Form::hidden('field_id', $field->id) !!}
                <div class='btn-group'>
                    {{--{!! Form::button('<i class="glyphicon glyphicon-trash"></i>',
                                     ['type' => 'submit',
                                      'class' => 'btn btn-danger btn-xs'])
                      !!}--}}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
</div>

resources/views/admin/pireps/fields.blade.php
<div class="row">
    <div class="form-group col-sm-12">
        {{--<div class="avatar">
            <img src="{!! $pirep->pilot->gravatar() !!}" />
        </div>--}}
        Filed By: <a href="{!! route('admin.users.edit', [$pirep->pilot->id]) !!}" target="_blank">
            {!! $pirep->pilot->pilot_id() !!} {!! $pirep->pilot->name !!}
        </a>
    </div>

    <div class="form-group col-sm-6">
        <div>
        {!! Form::label('airline_id', 'Airline') !!}
        {!! Form::select('airline_id', $airlines, null, ['class' => 'form-control select2']) !!}
        </div>
        <br />
        <div>
        {!! Form::label('aircraft_id', 'Aircraft:') !!}
        {!! Form::select('aircraft_id', $aircraft, null, ['class' => 'form-control select2']) !!}
        </div>
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('flight_number', 'Flight Number/Route Code/Leg') !!}
        {!! Form::text('flight_number', null, ['placeholder' => 'Flight Number', 'class' => 'form-control']) !!}
        {!! Form::text('route_code', null, ['placeholder' => 'Code (optional)', 'class' => 'form-control']) !!}
        {!! Form::text('route_leg', null, ['placeholder' => 'Leg (optional)', 'class' => 'form-control']) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('dpt_airport_id', 'Departure Airport:') !!}
        {!! Form::select('dpt_airport_id', $airports, null, ['class' => 'form-control select2']) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('arr_airport_id', 'Arrival Airport:') !!}
        {!! Form::select('arr_airport_id', $airports, null, ['class' => 'form-control select2']) !!}
    </div>

    <!-- Flight Time Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('flight_time', 'Flight Time (hours & minutes):') !!}
        <div class="">
            {!! Form::number('hours', null, ['class' => 'form-control', 'placeholder' => 'hours']) !!}
            {!! Form::number('minutes', null, ['class' => 'form-control', 'placeholder' => 'minutes']) !!}
        </div>
    </div>

    <!-- Level Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('level', 'Flight Level:') !!}
        {!! Form::text('level', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Route Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('route', 'Route:') !!}
        {!! Form::text('route', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Notes Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('notes', 'Notes:') !!}
        {!! Form::textarea('notes', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Raw Data Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('raw_data', 'Raw Data:') !!}
        {!! Form::textarea('raw_data', null, ['class' => 'form-control', 'disabled']) !!}
    </div>

<!-- Submit Field -->
    <div class="form-group col-sm-12">
        <div class="pull-right">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{!! route('admin.pireps.index') !!}" class="btn btn-default">Cancel</a>
        </div>
    </div>
</div>

resources/views/admin/pireps/index.blade.php
@extends('admin.app')

@section('title', 'Pilot Reports')
@section('actions')
    <li><a href="{!! route('admin.pireps.index') !!}?search=status:0"><i class="ti-plus"></i>Pending</a></li>
    <li><a href="{!! route('admin.pireps.index') !!}"><i class="ti-plus"></i>View All</a></li>
@endsection
@section('content')
    @include('admin.pireps.table')

    <div class="row">
        <div class="col-12 text-center">
            {{ $pireps->links('admin.pagination.default') }}
        </div>
    </div>
@endsection
@include('admin.pireps.script')

resources/views/admin/pireps/script.blade.php
@section('scripts')
<script>
function changeStatus(values) {
    var destContainer = '#pirep_' + values.pirep_id + '_container';
    $.ajax({
        url: '/admin/pireps/' + values.pirep_id + '/status',
        data: values,
        type: 'POST',
        success: function (data) {
            // console.log(data);
            $(destContainer).replaceWith(data);
        }
    });
}

//$(document).ready(function() {
    $(document).on('submit', 'form.pirep_submit_status', function (event) {
        console.log(event);

        event.preventDefault();
        var values = {
            pirep_id: $(this).attr('pirep_id'),
            new_status: $(this).attr('new_status')
        };

        console.log(values);
        console.log('Changing PIREP ' + values.pirep_id + ' to state ' + values.new_status);

        //var destContainer = '#pirep_' + pirep_id + '_container';
        //$.pjax.submit(event, destContainer, { push: false, maxCacheLength: 0 });

        changeStatus(values);
    });
//});
</script>
@endsection

resources/views/admin/pireps/show.blade.php
@extends('admin.app')
@section('title', 'pilot report')
@section('actions')
    <li><a href="#"><i class="ti-plus"></i>Accept</a></li>
    <li><a href="#"><i class="ti-plus"></i>Reject</a></li>
@endsection

@section('content')
    <div class="card">
        @include('admin.pireps.show_fields')
        @include('admin.pireps.field_values')
    </div>
@endsection

resources/views/admin/pireps/show_fields.blade.php
<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            {{--<i class="fa fa-text-width"></i>--}}
            <h3 class="box-title">{!! Form::label('dpt_airport_id', 'Dep ICAO') !!}</h3>
        </div>
        <div class="box-body"><p class="lead">
                {!! $pirep->dpt_airport->icao !!} - {!! $pirep->dpt_airport->name !!}
        </p></div>
    </div>
</div>

<div class="form-group col-sm-6">
    <div class="box box-solid">
        <div class="box-header with-border">
            {{--<i class="fa fa-text-width"></i>--}}
            <h3 class="box-title">{!! Form::label('arr_airport_id', 'Arrival ICAO') !!}</h3>
        </div>
        <div class="box-body"><p class="lead">
                {!! $pirep->arr_airport->icao !!} - {!! $pirep->arr_airport->name !!}
            </p>
        </div>
    </div>
</div>


<div class="form-group col-sm-12">
    <div class="box box-primary">
        <div class="box-body">

            <!-- User Id Field -->
            <div class="form-group">
                {!! Form::label('user_id', 'Pilot:') !!}
                <p>{!! $pirep->user->name !!}</p>
            </div>

            <!-- Flight Id Field -->
            <div class="form-group">
                {!! Form::label('flight_id', 'Flight Id:') !!}
                <p>
                    <a href="{!! route('admin.flights.show', [$pirep->flight_id]) !!}" target="_blank">
                        {!! $pirep->airline->code !!}
                        @if($pirep->flight_id)
                            {!! $pirep->flight->flight_number !!}
                        @else
                            {!! $pirep->flight_number !!}
                        @endif
                    </a>
                </p>
            </div>

            <!-- Aircraft Id Field -->
            <div class="form-group">
                {!! Form::label('aircraft_id', 'Aircraft:') !!}
                <p>{!! $pirep->aircraft->subfleet->name !!}, {!! $pirep->aircraft->name !!}
                    ({!! $pirep->aircraft->registration !!})
                </p>
            </div>

            <!-- Flight Time Field -->
            <div class="form-group">
                {!! Form::label('flight_time', 'Flight Time:') !!}
                <p>{!! Utils::secondsToTime($pirep->flight_time) !!}</p>
            </div>

            <!-- Level Field -->
            <div class="form-group">
                {!! Form::label('level', 'Level:') !!}
                <p>{!! $pirep->level !!}</p>
            </div>

            <!-- Route Field -->
            <div class="form-group">
                {!! Form::label('route', 'Route:') !!}
                <p>{!! $pirep->route !!}</p>
            </div>

            <!-- Notes Field -->
            <div class="form-group">
                {!! Form::label('notes', 'Notes:') !!}
                <p>{!! $pirep->notes !!}</p>
            </div>

            <!-- Raw Data Field -->
            <div class="form-group">
                {!! Form::label('raw_data', 'Raw Data:') !!}
                <p>{!! $pirep->raw_data !!}</p>
            </div>

            <!-- Created At Field -->
            <div class="form-group">
                {!! Form::label('created_at', 'Created At:') !!}
                <p>{!! $pirep->created_at !!}</p>
            </div>

            <!-- Updated At Field -->
            <div class="form-group">
                {!! Form::label('updated_at', 'Updated At:') !!}
                <p>{!! $pirep->updated_at !!}</p>
            </div>
        </div>
    </div>
</div>

resources/views/admin/pireps/table.blade.php
@each('admin.pireps.pirep_card', $pireps, 'pirep')